module.exports = {
  projects: [
    '<rootDir>/apps/coverme',
    '<rootDir>/apps/dchbx',
    '<rootDir>/apps/health-connector',
    '<rootDir>/libs/ui/base/theme',
    '<rootDir>/libs/ui/base/shell',
    '<rootDir>/libs/testing/i18n',
    '<rootDir>/libs/i18n/coverme',
    '<rootDir>/libs/i18n/util',
    '<rootDir>/libs/financial-assistance/shell',
    '<rootDir>/libs/financial-assistance/applications',
    '<rootDir>/libs/financial-assistance/entities',
    '<rootDir>/libs/financial-assistance/applicant',
    '<rootDir>/libs/financial-assistance/data-access',
    '<rootDir>/libs/util/transforms',
    '<rootDir>/libs/shared/state/root-store',
    '<rootDir>/libs/i18n/dchbx',
    '<rootDir>/libs/i18n/shared',
    '<rootDir>/libs/testing/stubs/financial-assistance',
    '<rootDir>/libs/financial-assistance/store/applicants',
    '<rootDir>/libs/testing/e2e',
    '<rootDir>/libs/shared/analytics',
    '<rootDir>/libs/shared/title',
    '<rootDir>/libs/util/helpers',
  ],
};
