module.exports = {
  projects: [
    '<rootDir>/apps/coverme',
    '<rootDir>/apps/dchbx',
    '<rootDir>/apps/health-connector',
    '<rootDir>/libs/ui/base/shell',
    '<rootDir>/libs/testing/i18n',
    '<rootDir>/libs/i18n/coverme',
    '<rootDir>/libs/financial-assistance/shell',
    '<rootDir>/libs/financial-assistance/applications',
    '<rootDir>/libs/financial-assistance/entities',
    '<rootDir>/libs/financial-assistance/applicant',
    '<rootDir>/libs/financial-assistance/data-access',
    '<rootDir>/libs/util/transforms',
    '<rootDir>/libs/shared/state/root-store',
    '<rootDir>/libs/financial-assistance/store/applicants',
    '<rootDir>/libs/shared/analytics',
    '<rootDir>/libs/util/helpers',
    '<rootDir>/libs/shared/page-title',
    '<rootDir>/libs/financial-assistance/testing',
    '<rootDir>/libs/coverme/i18n',
    '<rootDir>/libs/dchbx/i18n',
    '<rootDir>/libs/shared/i18n',
    '<rootDir>/libs/shared/theme',
  ],
};
