name: pull request checks

on:
  pull_request:
    branches:
      - trunk

concurrency:
  group: dte-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.0
    with:
      number-of-agents: 3
      main-branch-name: trunk
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      artifacts-path: dist/apps
      artifacts-name: affected-apps

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.0
    with:
      number-of-agents: 3
