name: deploy to aws

on:
  push:
    branches:
      - trunk

concurrency:
  group: aws-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: v3-${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v3-${{ runner.os }}-node16-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i --force
      - name: Build Application(s)
        run: npx nx run console:build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: affected-apps
          path: dist/apps/console
  deploy:
    name: Deploy affected applications
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: affected-apps
          path: dist/apps/console
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: deploy
        # run: npx nx console:deploy --env=preprod --cloudfrontId=E5RER2GERTJUC
        run: |
          cd dist/apps/console
          aws s3 sync . s3://cme-console-preprod/ --delete
          invalidationId=`AWS_MAX_ATTEMPTS=999 aws cloudfront create-invalidation --distribution-id E5RER2GERTJUC --output text --query 'Invalidation.Id' --paths '/*'`
          aws cloudfront wait invalidation-completed --distribution-id E5RER2GERTJUC --id ${invalidationId}
