name: test and deploy front end

on:
  push:
    branches:
      - trunk

concurrency:
  group: qb-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'trunk'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: v3-${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v3-${{ runner.os }}-node16-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Check formatting
        run: npx nx format:check
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'trunk'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: v3-${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v3-${{ runner.os }}-node16-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Lint Application(s)
        run: npx nx workspace-lint
      - run: npx nx affected --target=lint --parallel=3
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'trunk'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: v3-${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v3-${{ runner.os }}-node16-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Test Application(s)
        run: npx nx affected --target=test --parallel=3 --ci
  # e2e:
  #   name: e2e
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Derive appropriate SHAs for base and head for `nx affected` commands
  #       uses: nrwl/nx-set-shas@v2
  #       with:
  #         main-branch-name: 'trunk'
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.x'
  #     - name: Cache node_modules
  #       uses: actions/cache@v3
  #       id: npm-cache
  #       with:
  #         path: node_modules
  #         key: v3-${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           v3-${{ runner.os }}-node16-
  #     - name: Cache cypress
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.cache/Cypress
  #         key: cypress-cache-v7-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: |
  #           cypress-cache-v7-${{ runner.os }}
  #     - name: Install dependencies
  #       if: steps.npm-cache.outputs.cache-hit != 'true'
  #       run: npm i
  #     - name: Run e2e Tests
  #       run: npx nx affected --target=e2e --parallel=3
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'trunk'
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: v3-${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v3-${{ runner.os }}-node16-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i
      - name: Build Application(s)
        run: npx nx affected --target=build --parallel=3
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: affected-apps
          path: dist/apps
  deploy:
    name: Deploy affected applications
    needs: [format, lint, test, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: affected-apps
          path: dist/apps
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: v3-${{ runner.os }}-node16-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v3-${{ runner.os }}-node16-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm i
      - name: run many deployments
        run: npx nx affected --target=deploy --parallel=3
      # - uses: FirebaseExtended/action-hosting-deploy@v0
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ENROLL_FE }}'
      #     channelId: live
      #     projectId: enroll-fe
