name: test and deploy front end

on:
  push:
    # branches:
    #   - trunk

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-${{ runner.os }}-node14-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Check formatting
        run: npm run format:check
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-${{ runner.os }}-node14-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint Application(s)
        run: npx nx affected:lint --base=origin/trunk~1 --head=origin/trunk --parallel
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-${{ runner.os }}-node14-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test Application(s)
        run: npx nx affected:test --base=origin/trunk~1 --head=origin/trunk --parallel
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Cache node_modules
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-${{ runner.os }}-node14-
      - name: Cache cypress
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-cache-v2-${{ runner.os }}
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run e2e Tests
        run: npx nx affected:e2e --base=origin/trunk~1 --head=origin/trunk --parallel --browser=chrome --headless=true
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-${{ runner.os }}-node14-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Application(s)
        run: npx nx affected:build --base=origin/trunk~1 --head=origin/trunk --parallel
  deploy:
    name: deploy
    needs: [format, lint, test, e2e, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: node_modules
          key: v2-${{ runner.os }}-node14-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            v2-${{ runner.os }}-node14-
      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Deploy Application(s)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npx nx affected --target=deploy --base=origin/trunk~1 --head=origin/trunk
